# Generated by Django 4.2.7 on 2025-11-02 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pno', models.CharField(max_length=20, unique=True, verbose_name='Personnel Number')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_number', models.CharField(max_length=50, unique=True)),
                ('aircraft_type', models.CharField(choices=[('FIGHTER', 'Fighter Aircraft'), ('TRANSPORT', 'Transport Aircraft'), ('HELICOPTER', 'Helicopter'), ('TRAINER', 'Trainer Aircraft'), ('RECONNAISSANCE', 'Reconnaissance Aircraft')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('GROUNDED', 'Grounded')], default='OPERATIONAL', max_length=20)),
                ('total_flying_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, help_text='In Liters', max_digits=10)),
                ('current_fuel_level', models.DecimalField(decimal_places=2, default=0, help_text='In Liters', max_digits=10)),
                ('tire_pressure_main', models.DecimalField(decimal_places=2, default=0, help_text='PSI', max_digits=5)),
                ('tire_pressure_nose', models.DecimalField(decimal_places=2, default=0, help_text='PSI', max_digits=5)),
                ('date_of_manufacture', models.DateField(blank=True, null=True)),
                ('date_of_induction', models.DateField(blank=True, null=True)),
                ('last_major_overhaul', models.DateField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['aircraft_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Routine Inspection'), ('SCHEDULED', 'Scheduled Maintenance'), ('MAJOR', 'Major Overhaul'), ('EMERGENCY', 'Emergency Repair')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('description', models.TextField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='aviation_app.aircraft')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitation_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imposed_date', models.DateField()),
                ('lifted_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitations', to='aviation_app.aircraft')),
                ('imposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limitations_imposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limitation',
                'verbose_name_plural': 'Limitations',
                'ordering': ['-imposed_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadingParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=100)),
                ('engine_serial_number', models.CharField(max_length=100)),
                ('airframe_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('engine_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('propeller_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('maximum_takeoff_weight', models.DecimalField(decimal_places=2, help_text='In KG', max_digits=10)),
                ('maximum_landing_weight', models.DecimalField(decimal_places=2, help_text='In KG', max_digits=10)),
                ('fuel_tank_capacity', models.DecimalField(decimal_places=2, help_text='In Liters', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leading_particulars', to='aviation_app.aircraft')),
            ],
            options={
                'verbose_name': 'Leading Particulars',
                'verbose_name_plural': 'Leading Particulars',
            },
        ),
        migrations.CreateModel(
            name='FlyingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('TRAINING', 'Training'), ('COMBAT', 'Combat'), ('TRANSPORT', 'Transport'), ('RECONNAISSANCE', 'Reconnaissance'), ('PATROL', 'Patrol'), ('OTHER', 'Other')], max_length=50)),
                ('flight_date', models.DateField()),
                ('takeoff_time', models.TimeField()),
                ('landing_time', models.TimeField()),
                ('flight_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('departure_location', models.CharField(max_length=100)),
                ('arrival_location', models.CharField(max_length=100)),
                ('fuel_consumed', models.DecimalField(decimal_places=2, help_text='In Liters', max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flying_operations', to='aviation_app.aircraft')),
                ('co_pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_co_piloted', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_piloted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flying Operation',
                'verbose_name_plural': 'Flying Operations',
                'ordering': ['-flight_date', '-takeoff_time'],
            },
        ),
        migrations.CreateModel(
            name='DeferredDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DEFERRED', 'Deferred')], default='OPEN', max_length=20)),
                ('reported_date', models.DateField()),
                ('deferred_until', models.DateField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('resolution_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_defects', to='aviation_app.aircraft')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deferred Defect',
                'verbose_name_plural': 'Deferred Defects',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_month', models.DateField()),
                ('estimated_flying_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_maintenance_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('major_maintenance_due', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_forecasts', to='aviation_app.aircraft')),
            ],
            options={
                'verbose_name': 'Maintenance Forecast',
                'verbose_name_plural': 'Maintenance Forecasts',
                'ordering': ['forecast_month'],
                'unique_together': {('aircraft', 'forecast_month')},
            },
        ),
    ]
