# Generated by Django 4.2.7 on 2025-11-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeFlyingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FSI_APPROVED', 'FSI Approved')], default='IN_PROGRESS', max_length=20)),
                ('ae_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('ae_signed_at', models.DateTimeField(blank=True, null=True)),
                ('al_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('al_signed_at', models.DateTimeField(blank=True, null=True)),
                ('ao_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('ao_signed_at', models.DateTimeField(blank=True, null=True)),
                ('ar_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('ar_signed_at', models.DateTimeField(blank=True, null=True)),
                ('se_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('se_signed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_required', models.BooleanField(default=False)),
                ('supervisor_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('supervisor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('fsi_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('fsi_signed_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_level_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tire_pressure_main_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tire_pressure_nose_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ae_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_ae_signed', to=settings.AUTH_USER_MODEL)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bfs_records', to='aviation_app.aircraft')),
                ('al_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_al_signed', to=settings.AUTH_USER_MODEL)),
                ('ao_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_ao_signed', to=settings.AUTH_USER_MODEL)),
                ('ar_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_ar_signed', to=settings.AUTH_USER_MODEL)),
                ('fsi_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_fsi_signed', to=settings.AUTH_USER_MODEL)),
                ('se_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_se_signed', to=settings.AUTH_USER_MODEL)),
                ('supervisor_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_supervisor_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Before Flying Service',
                'verbose_name_plural': 'Before Flying Services',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='PilotAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('pilot_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('pilot_signed_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_level_check', models.BooleanField(default=False)),
                ('tire_pressure_check', models.BooleanField(default=False)),
                ('engine_check', models.BooleanField(default=False)),
                ('controls_check', models.BooleanField(default=False)),
                ('instruments_check', models.BooleanField(default=False)),
                ('communication_check', models.BooleanField(default=False)),
                ('current_fuel_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_tire_pressure_main', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_tire_pressure_nose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_acceptances', to='aviation_app.aircraft')),
                ('bfs_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_acceptance', to='aviation_app.beforeflyingservice')),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Acceptance',
                'verbose_name_plural': 'Pilot Acceptances',
                'ordering': ['-acceptance_date'],
            },
        ),
        migrations.CreateModel(
            name='PostFlying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_flight_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('flight_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_level_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tire_pressure_main_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tire_pressure_nose_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('engine_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('issues_found', models.TextField(blank=True, null=True)),
                ('defects_reported', models.BooleanField(default=False)),
                ('pilot_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('pilot_signed_at', models.DateTimeField(blank=True, null=True)),
                ('engineer_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('engineer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_flying_records', to='aviation_app.aircraft')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_flight_engineer_signed', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_flight_signed', to=settings.AUTH_USER_MODEL)),
                ('pilot_acceptance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_flying', to='aviation_app.pilotacceptance')),
            ],
            options={
                'verbose_name': 'Post Flying',
                'verbose_name_plural': 'Post Flying Records',
                'ordering': ['-post_flight_date'],
            },
        ),
    ]
