# Generated by Django 4.2.7 on 2025-11-04 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviation_app', '0002_beforeflyingservice_pilotacceptance_postflying'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeflyingservice',
            name='assigned_ae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_assigned_ae', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='assigned_al',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_assigned_al', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='assigned_ao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_assigned_ao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='assigned_ar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_assigned_ar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='assigned_se',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_assigned_se', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_assigned_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='fsi_initial_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='fsi_initial_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bfs_fsi_initial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='fsi_initial_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beforeflyingservice',
            name='personnel_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postflying',
            name='flight_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postflying',
            name='number_of_landings',
            field=models.IntegerField(default=0, help_text='Number of landings during flight'),
        ),
        migrations.AddField(
            model_name='postflying',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason for flight termination', null=True),
        ),
        migrations.AlterField(
            model_name='beforeflyingservice',
            name='status',
            field=models.CharField(choices=[('FSI_INITIAL', 'FSI Initial Authentication'), ('PERSONNEL_SELECTION', 'Personnel Selection'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FSI_APPROVED', 'FSI Approved')], default='FSI_INITIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='postflying',
            name='flight_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='postflying',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='postflying',
            name='fuel_level_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='postflying',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='IN_PROGRESS', max_length=20),
        ),
    ]
